[![](https://dnc.eclecity.net/wp-content/uploads/2016/03/economy-crisis-2-1236979-1600x1200-732x549.jpg)](https://dnc.eclecity.net/wp-content/uploads/2016/03/economy-crisis-2-1236979-1600x1200.jpg "It’s not about the EU") 

Here are two statements, both of which I believe to be true:

1.  If Britain stays in the EU, life will continue to get harder for ordinary British people. That’s one of the points the Leavers have been trying to make right from the start.
2.  If Britain quits the EU life will also continue to get harder for ordinary British people. There’s no difference except for how fast it happens.

Why do I believe things will get worse whether we leave or stay? Well, the simple answer is that it’s mostly not about the EU. Here’s why.

The belief among many British people is that things have been going downhill ever since we joined the EU, so either something should be done to fix the EU or we should leave. But have we really been putting up with this situation for 40 years? It seems to me that most of the shouting started in about 2008, which is when the economic crisis hit. Up to then we were on a roll. All through the Thatcher to Blair period salaries rocketed, and right up to the end house prices were booming. I well remember right before the crash people talking confidently about retiring at 55 and moving abroad to the sun. That didn’t sound like such a bad deal and the EU, though it came in for some criticism, was on the whole working pretty well. Especially when it did good things like stopping the French from banning our beef following the mad cow crisis.

Everything changed in 2008 and although the cause of the recession was the international banking system, the blame gradually shifted to the EU in the minds of ordinary people. The reason isn’t hard to find; the tabloids saw an opportunity to stuff the EU they’ve always hated because it threatens their ability to behave exactly as they please. Anyone who tries to regulate the British press is going to have a hard time. As Mark Twain famously said, “Never pick a fight with a man who orders ink by the barrel”.

It wasn’t just in Britain that the EU lost popularity. Most other European countries experiencing the same hardships developed a core of EU-haters. And to many people that’s enough to prove what they believe; that the EU is responsible for this mess because it’s costly, inefficient, corrupt and unnecessary.

The only problem with this is that the difficulties facing ordinary people in Britain, France or Italy are also felt by people in countries that aren’t part of the EU, or in some cases of any large trading bloc. Americans are suffering too; their economy is in an even worse state than that of Europe, and Japan has been mired in stagnation for the best part of 20 years. How can the EU be held responsible for that?

So before we hastily leap to conclusions and make a decision that won’t improve matters and could make them a lot worse, let’s look at what’s really causing us all to feel poor and hard done-by.

The big question is “Where has all the money gone?”. Money doesn’t just vanish; it all goes somewhere. I think of it like engine oil. If you keep it in a can on the supermarket shelf or in your garage it’s not doing anything. It only has any purpose when it’s keeping your engine running. And the problem today is the “oil” isn’t in the engine.

![oil](http://dnc.eclecity.net/wp-content/uploads/2016/03/oil-300x300.png)

Put money into the economy and lots of things happen. For example, build a new town, a railway line or a road network. Invest in high-speed fibre internet for everyone. Get a major drug discovery programme running. It doesn’t really matter where you start; it all kick-starts the economy. Buildings have to be constructed; drains dug, cables laid. Each of these needs companies specialising in that particular area. Eventually, ordinary working people get paid; they go to the supermarket or the department store and buy things. Every sector of the economy gets involved as the vital lubricant flows through it.

Instead, what we have is something described as “austerity”. This is the biggest con trick ever pulled on ordinary people. For “austerity” is just for people who don’t get to make decisions about how their lives are run. Employees, retired people, the unemployed, the sick… none of these have any say in the process. Budgets are cut, pay rates reduced and benefits squeezed. The oil is being drained out of the engine. And where’s it going? That’s the crux of the matter.

The truth is it’s going to people who already have more than they need. And because they have so much, all this extra “oil” is going onto shelves, where it does nothing to help the engine. Or, if you prefer, the money is going into bank accounts that are already bursting with funds. The wealthy are getting richer. It’s been happening for several decades but now it’s on overdrive. The wealthiest people now have sums of money that are beyond our ability to grasp. What is a billion pounds? What could you possibly spend it on? Well you couldn’t; all you can do is keep it in the bank. And because it’s all in the bank accounts of a very few people it’s not available to help the economy run, so everything grinds to a near halt.

I live near the Riviera, not far from Monaco. Sounds glamorous, doesn’t it? But it’s a well-known fact that people in Monaco never pay for anything. Every day there’s a new art exhibition somewhere in the city, where some artist is desperately trying to make that all-important breakthrough. They lay on champagne and snacks and all the same familiar faces appear, day after day, to tuck into all this free food and drink, often without so much as a glance at the paintings on display. And I’m not talking about the poor; most of these people are millionaires or better. They are so used to having a free ride it becomes a drug.

This may be happening in the EU but it’s part of a global problem. The more that wealth gets concentrated into fewer and fewer hands the poorer we all get. It’s a natural reaction to blame somebody and the UK press has targeted the EU as the scapegoat. The result is Brexit. And afterwards, cold reality will set in, that it was nothing to do with the EU in the first place. We aren’t going to get any better off.

It gets worse, because the people who wanted us to exit will now be in power. They never wanted to improve the lives of the masses; their aim remains to complete their mission to take control, so they can do whatever they like without interference from Brussels. Inconvenient directives like the imposition of a maximum working week will be swept away, along with consumer protection and all the other many things the EU has done for the ordinary people of Europe but which have been completely misrepresented by the British press. Multinational corporations need low-cost labour and as few regulations as possible. In the Far East, labour costs are rising. So let’s see how far we can drive down the cost of labour in Britain, shall we?

All of this has been happening while we were a member of the EU. It’s been happening in the USA too. I’m not claiming the EU will protect us totally from the harsher effects of globalisation. They’re far from perfect but at least they want to try. On our own there’s just us, alone against forces immensely bigger than we are. Global business doesn’t care about British people, only about profit. The EU is big enough to hamper their efforts, but we aren’t.

So when you hear stockbrokers and businessmen banging on about “wanting our county back”, ask yourself who gets to benefit. Is it you? Or is it just them? Then think carefully on June 23 before giving them what they want; once you’ve handed everything to them you won’t get the chance to take it back again.