#!/bin/sh

mkdir -p ~/temp/lib
rm -rf ~/temp/lib
mkdir -p ~/temp/plugins
cd ~/Dropbox/Code/VisualStudio/EasyCoder/EasyCoder

cp js/plugins/* ~/EasyCoder/easycoder/plugins
cp server/* ~/EasyCoder/easycoder

cat js/easycoder/*.js js/EasyCoder.js > ~/EasyCoder/easycoder/easycoder.js
cat js/plugins/browser.js js/plugins/json.js js/plugins/rest.js js/plugins/ckeditor.js js/plugins/gmap.js js/plugins/showdown.js js/plugins/codemirror.js js/plugins/svg.js js/plugins/ui.js js/plugins/wof.js js/plugins/anagrams.js js/plugins-all.js js/easycoder/*.js js/EasyCoder-Cordova.js > ~/EasyCoder/easycoder/easycoder-cordova.js
echo "Merge completed"

cd ~/EasyCoder
npx google-closure-compiler --js=easycoder/easycoder.js --js_output_file=easycoder/easycoder-min.js --language_in ECMASCRIPT_2018
echo "Closure finished"

cp easycoder/easycoder.js ~/Dropbox/Code/VisualStudio/EasyCoder/EasyCoder/easycoder/easycoder.js
cp easycoder/easycoder-min.js ~/Dropbox/Code/VisualStudio/EasyCoder/EasyCoder/easycoder/easycoder-min.js
cp -R easycoder/plugins ~/Dropbox/Code/VisualStudio/EasyCoder/EasyCoder/easycoder
rm easycoder.zip
zip -r easycoder.zip *
cp easycoder.zip ~/Dropbox/Code/VisualStudio/EasyCoder
echo "Files copied"

rm -rf ~/temp/lib
echo "All done"
