#!/bin/sh

echo "Copy the various files"
cd ~/dev/easycoder/easycoder.github.io
rm -rf dist/*
mkdir dist/plugins
cp -r js/plugins/* dist/plugins
cp -r server/* dist

echo "Merge into a single file"
cat js/easycoder/Core.js js/easycoder/Browser.js js/easycoder/MarkdownRenderer.js js/easycoder/JSON.js js/easycoder/MQTT.js js/easycoder/REST.js js/easycoder/Compare.js js/easycoder/Condition.js js/easycoder/Value.js js/easycoder/Run.js js/easycoder/Compile.js js/easycoder/Main.js js/easycoder/EasyCoder.js > dist/easycoder.js

echo "Minimise with closure"
npx google-closure-compiler --js=dist/easycoder.js --js_output_file=dist/easycoder-min.js --language_in ECMASCRIPT_2018
echo "Closure finished"
